// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// lr_create
SEXP lr_create();
RcppExport SEXP _VectorForgeML_lr_create() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(lr_create());
    return rcpp_result_gen;
END_RCPP
}
// lr_fit
void lr_fit(SEXP ptr, NumericMatrix X, NumericVector y);
RcppExport SEXP _VectorForgeML_lr_fit(SEXP ptrSEXP, SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    lr_fit(ptr, X, y);
    return R_NilValue;
END_RCPP
}
// lr_predict
NumericVector lr_predict(SEXP ptr, NumericMatrix X);
RcppExport SEXP _VectorForgeML_lr_predict(SEXP ptrSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(lr_predict(ptr, X));
    return rcpp_result_gen;
END_RCPP
}
// fastLm
NumericVector fastLm(NumericMatrix X, NumericVector y);
RcppExport SEXP _VectorForgeML_fastLm(SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(fastLm(X, y));
    return rcpp_result_gen;
END_RCPP
}
// cpp_scale_fit_transform
List cpp_scale_fit_transform(NumericMatrix X, double eps);
RcppExport SEXP _VectorForgeML_cpp_scale_fit_transform(SEXP XSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_scale_fit_transform(X, eps));
    return rcpp_result_gen;
END_RCPP
}
// cpp_scale_transform
NumericMatrix cpp_scale_transform(NumericMatrix X, NumericVector means, NumericVector sds, double eps);
RcppExport SEXP _VectorForgeML_cpp_scale_transform(SEXP XSEXP, SEXP meansSEXP, SEXP sdsSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type means(meansSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sds(sdsSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_scale_transform(X, means, sds, eps));
    return rcpp_result_gen;
END_RCPP
}
// cpp_drop_constant_cols
List cpp_drop_constant_cols(NumericMatrix X, double eps);
RcppExport SEXP _VectorForgeML_cpp_drop_constant_cols(SEXP XSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_drop_constant_cols(X, eps));
    return rcpp_result_gen;
END_RCPP
}
// logreg_create
SEXP logreg_create();
RcppExport SEXP _VectorForgeML_logreg_create() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(logreg_create());
    return rcpp_result_gen;
END_RCPP
}
// logreg_fit
void logreg_fit(SEXP ptr, NumericMatrix X, NumericVector y, double lr, int epochs);
RcppExport SEXP _VectorForgeML_logreg_fit(SEXP ptrSEXP, SEXP XSEXP, SEXP ySEXP, SEXP lrSEXP, SEXP epochsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type lr(lrSEXP);
    Rcpp::traits::input_parameter< int >::type epochs(epochsSEXP);
    logreg_fit(ptr, X, y, lr, epochs);
    return R_NilValue;
END_RCPP
}
// logreg_predict
NumericVector logreg_predict(SEXP ptr, NumericMatrix X);
RcppExport SEXP _VectorForgeML_logreg_predict(SEXP ptrSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(logreg_predict(ptr, X));
    return rcpp_result_gen;
END_RCPP
}
// logreg_predict_proba
NumericVector logreg_predict_proba(SEXP ptr, NumericMatrix X);
RcppExport SEXP _VectorForgeML_logreg_predict_proba(SEXP ptrSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(logreg_predict_proba(ptr, X));
    return rcpp_result_gen;
END_RCPP
}
// softmax_create
SEXP softmax_create();
RcppExport SEXP _VectorForgeML_softmax_create() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(softmax_create());
    return rcpp_result_gen;
END_RCPP
}
// softmax_fit
void softmax_fit(SEXP ptr, NumericMatrix X, IntegerVector y, double lr, int epochs);
RcppExport SEXP _VectorForgeML_softmax_fit(SEXP ptrSEXP, SEXP XSEXP, SEXP ySEXP, SEXP lrSEXP, SEXP epochsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type lr(lrSEXP);
    Rcpp::traits::input_parameter< int >::type epochs(epochsSEXP);
    softmax_fit(ptr, X, y, lr, epochs);
    return R_NilValue;
END_RCPP
}
// softmax_predict
IntegerVector softmax_predict(SEXP ptr, NumericMatrix X);
RcppExport SEXP _VectorForgeML_softmax_predict(SEXP ptrSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(softmax_predict(ptr, X));
    return rcpp_result_gen;
END_RCPP
}
// softmax_predict_proba
NumericMatrix softmax_predict_proba(SEXP ptr, NumericMatrix X);
RcppExport SEXP _VectorForgeML_softmax_predict_proba(SEXP ptrSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(softmax_predict_proba(ptr, X));
    return rcpp_result_gen;
END_RCPP
}
// square_vec
NumericVector square_vec(NumericVector x);
RcppExport SEXP _VectorForgeML_square_vec(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(square_vec(x));
    return rcpp_result_gen;
END_RCPP
}
// sum2
int sum2(int x, int y);
RcppExport SEXP _VectorForgeML_sum2(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(sum2(x, y));
    return rcpp_result_gen;
END_RCPP
}
// cpp_sum_squares
double cpp_sum_squares(int n);
RcppExport SEXP _VectorForgeML_cpp_sum_squares(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_sum_squares(n));
    return rcpp_result_gen;
END_RCPP
}
// dot_product
double dot_product(NumericVector a, NumericVector b);
RcppExport SEXP _VectorForgeML_dot_product(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(dot_product(a, b));
    return rcpp_result_gen;
END_RCPP
}
// cpp_set_blas_threads
void cpp_set_blas_threads();
RcppExport SEXP _VectorForgeML_cpp_set_blas_threads() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    cpp_set_blas_threads();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_VectorForgeML_lr_create", (DL_FUNC) &_VectorForgeML_lr_create, 0},
    {"_VectorForgeML_lr_fit", (DL_FUNC) &_VectorForgeML_lr_fit, 3},
    {"_VectorForgeML_lr_predict", (DL_FUNC) &_VectorForgeML_lr_predict, 2},
    {"_VectorForgeML_fastLm", (DL_FUNC) &_VectorForgeML_fastLm, 2},
    {"_VectorForgeML_cpp_scale_fit_transform", (DL_FUNC) &_VectorForgeML_cpp_scale_fit_transform, 2},
    {"_VectorForgeML_cpp_scale_transform", (DL_FUNC) &_VectorForgeML_cpp_scale_transform, 4},
    {"_VectorForgeML_cpp_drop_constant_cols", (DL_FUNC) &_VectorForgeML_cpp_drop_constant_cols, 2},
    {"_VectorForgeML_logreg_create", (DL_FUNC) &_VectorForgeML_logreg_create, 0},
    {"_VectorForgeML_logreg_fit", (DL_FUNC) &_VectorForgeML_logreg_fit, 5},
    {"_VectorForgeML_logreg_predict", (DL_FUNC) &_VectorForgeML_logreg_predict, 2},
    {"_VectorForgeML_logreg_predict_proba", (DL_FUNC) &_VectorForgeML_logreg_predict_proba, 2},
    {"_VectorForgeML_softmax_create", (DL_FUNC) &_VectorForgeML_softmax_create, 0},
    {"_VectorForgeML_softmax_fit", (DL_FUNC) &_VectorForgeML_softmax_fit, 5},
    {"_VectorForgeML_softmax_predict", (DL_FUNC) &_VectorForgeML_softmax_predict, 2},
    {"_VectorForgeML_softmax_predict_proba", (DL_FUNC) &_VectorForgeML_softmax_predict_proba, 2},
    {"_VectorForgeML_square_vec", (DL_FUNC) &_VectorForgeML_square_vec, 1},
    {"_VectorForgeML_sum2", (DL_FUNC) &_VectorForgeML_sum2, 2},
    {"_VectorForgeML_cpp_sum_squares", (DL_FUNC) &_VectorForgeML_cpp_sum_squares, 1},
    {"_VectorForgeML_dot_product", (DL_FUNC) &_VectorForgeML_dot_product, 2},
    {"_VectorForgeML_cpp_set_blas_threads", (DL_FUNC) &_VectorForgeML_cpp_set_blas_threads, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_VectorForgeML(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
