// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// square_vec
NumericVector square_vec(NumericVector x);
RcppExport SEXP _VectorForgeML_square_vec(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(square_vec(x));
    return rcpp_result_gen;
END_RCPP
}
// sum2
int sum2(int x, int y);
RcppExport SEXP _VectorForgeML_sum2(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(sum2(x, y));
    return rcpp_result_gen;
END_RCPP
}
// cpp_sum_squares
double cpp_sum_squares(int n);
RcppExport SEXP _VectorForgeML_cpp_sum_squares(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_sum_squares(n));
    return rcpp_result_gen;
END_RCPP
}
// dot_product
double dot_product(NumericVector a, NumericVector b);
RcppExport SEXP _VectorForgeML_dot_product(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(dot_product(a, b));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_VectorForgeML_square_vec", (DL_FUNC) &_VectorForgeML_square_vec, 1},
    {"_VectorForgeML_sum2", (DL_FUNC) &_VectorForgeML_sum2, 2},
    {"_VectorForgeML_cpp_sum_squares", (DL_FUNC) &_VectorForgeML_cpp_sum_squares, 1},
    {"_VectorForgeML_dot_product", (DL_FUNC) &_VectorForgeML_dot_product, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_VectorForgeML(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
