# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

square_vec <- function(x) {
    .Call(`_VectorForgeML_square_vec`, x)
}

sum2 <- function(x, y) {
    .Call(`_VectorForgeML_sum2`, x, y)
}

cpp_sum_squares <- function(n) {
    .Call(`_VectorForgeML_cpp_sum_squares`, n)
}

dot_product <- function(a, b) {
    .Call(`_VectorForgeML_dot_product`, a, b)
}

