# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lr_create <- function() {
    .Call(`_VectorForgeML_lr_create`)
}

lr_fit <- function(ptr, X, y) {
    invisible(.Call(`_VectorForgeML_lr_fit`, ptr, X, y))
}

lr_predict <- function(ptr, X) {
    .Call(`_VectorForgeML_lr_predict`, ptr, X)
}

fastLm <- function(X, y) {
    .Call(`_VectorForgeML_fastLm`, X, y)
}

cpp_scale_fit_transform <- function(X, eps = 1e-12) {
    .Call(`_VectorForgeML_cpp_scale_fit_transform`, X, eps)
}

cpp_scale_transform <- function(X, means, sds, eps = 1e-12) {
    .Call(`_VectorForgeML_cpp_scale_transform`, X, means, sds, eps)
}

cpp_drop_constant_cols <- function(X, eps = 1e-12) {
    .Call(`_VectorForgeML_cpp_drop_constant_cols`, X, eps)
}

logreg_create <- function() {
    .Call(`_VectorForgeML_logreg_create`)
}

logreg_fit <- function(ptr, X, y, lr = 0.1, epochs = 100L) {
    invisible(.Call(`_VectorForgeML_logreg_fit`, ptr, X, y, lr, epochs))
}

logreg_predict <- function(ptr, X) {
    .Call(`_VectorForgeML_logreg_predict`, ptr, X)
}

logreg_predict_proba <- function(ptr, X) {
    .Call(`_VectorForgeML_logreg_predict_proba`, ptr, X)
}

softmax_create <- function() {
    .Call(`_VectorForgeML_softmax_create`)
}

softmax_fit <- function(ptr, X, y, lr = 0.1, epochs = 200L) {
    invisible(.Call(`_VectorForgeML_softmax_fit`, ptr, X, y, lr, epochs))
}

softmax_predict <- function(ptr, X) {
    .Call(`_VectorForgeML_softmax_predict`, ptr, X)
}

softmax_predict_proba <- function(ptr, X) {
    .Call(`_VectorForgeML_softmax_predict_proba`, ptr, X)
}

square_vec <- function(x) {
    .Call(`_VectorForgeML_square_vec`, x)
}

sum2 <- function(x, y) {
    .Call(`_VectorForgeML_sum2`, x, y)
}

cpp_sum_squares <- function(n) {
    .Call(`_VectorForgeML_cpp_sum_squares`, n)
}

dot_product <- function(a, b) {
    .Call(`_VectorForgeML_dot_product`, a, b)
}

cpp_set_blas_threads <- function() {
    invisible(.Call(`_VectorForgeML_cpp_set_blas_threads`))
}

